const promptInput = document.getElementById("gen-prompt");
const sizeInput = document.getElementById("gen-size");
const detailInput = document.getElementById("gen-detail");
const generateButton = document.getElementById("gen-button");
const output = document.getElementById("gen-output");
const copyButton = document.getElementById("gen-copy");
const openButton = document.getElementById("gen-open");
const status = document.getElementById("gen-status");
const details = document.getElementById("gen-details");

const STORAGE_KEY = "stlStudio.generatedCode";

function setStatus(message, isError = false) {
  status.textContent = message;
  status.classList.toggle("error", isError);
}

function setDetails(message) {
  details.textContent = message;
}

function clamp(value, min, max) {
  return Math.min(Math.max(value, min), max);
}

function pickSize(prompt, fallback) {
  const match = prompt.match(/(\d{2,4})\s*mm\b/i);
  if (match) {
    const parsed = Number(match[1]);
    if (Number.isFinite(parsed)) {
      return clamp(parsed, 20, 400);
    }
  }
  return fallback;
}

function baseHeader(fn) {
  return `// Generated by STL Studio\n// Units: millimeters\n\n$fn = ${fn};\n`;
}

function wrapScaled(scale, body) {
  return `scale([${scale.toFixed(3)}, ${scale.toFixed(3)}, ${scale.toFixed(3)}]) {\n${body}\n}`;
}

function templateJet(scale) {
  const body = `module fuselage() {\n  hull() {\n    translate([0,0,0]) scale([4,1.2,1.2]) sphere(10);\n    translate([80,0,0]) scale([3,1.1,1.1]) sphere(8);\n    translate([140,0,0]) scale([2,1,1]) sphere(6);\n    translate([170,0,0]) scale([1.2,0.9,0.9]) sphere(4);\n  }\n}\n\nmodule canopy() {\n  translate([45,0,12])\n    scale([2.2,1.2,1])\n      sphere(8);\n}\n\nmodule wings() {\n  translate([40,0,4])\n    linear_extrude(height=3, center=true)\n      polygon(points=[[0,0],[90,35],[110,0],[90,-35]]);\n}\n\nmodule tail() {\n  translate([130,0,10])\n    rotate([0,90,0])\n      linear_extrude(height=4, center=true)\n        polygon(points=[[0,0],[18,6],[0,12]]);\n}\n\nunion() {\n  fuselage();\n  canopy();\n  wings();\n  tail();\n}\n`;
  return wrapScaled(scale, body);
}

function templateComputer(scale) {
  const body = `module monitor() {\n  cube([120, 8, 80]);\n  translate([56, -18, 5])\n    cube([8, 18, 40]);\n  translate([30, -45, 0])\n    cube([60, 45, 5]);\n}\n\nmodule keyboard() {\n  translate([20, -85, 0])\n    cube([80, 30, 6]);\n}\n\nmonitor();\nkeyboard();\n`;
  return wrapScaled(scale, body);
}

function templateRocket(scale) {
  const body = `module rocket() {\n  cylinder(h=90, r=12);\n  translate([0,0,90])\n    cylinder(h=24, r1=12, r2=0);\n  for (a = [0:120:359]) {\n    rotate([0,0,a])\n      translate([12,0,20])\n        cube([8,2,24]);\n  }\n}\n\nrocket();\n`;
  return wrapScaled(scale, body);
}

function templateRing(scale) {
  const body = `difference() {\n  cylinder(h=8, r=24, center=true);\n  cylinder(h=12, r=16, center=true);\n}\n`;
  return wrapScaled(scale, body);
}

function templateVase(scale) {
  const body = `rotate_extrude(angle=360)\n  polygon(points=[\n    [0,0],[18,0],[20,8],[14,28],[22,55],[0,55]\n  ]);\n`;
  return wrapScaled(scale, body);
}

function templatePhoneStand(scale) {
  const body = `module stand() {\n  hull() {\n    translate([0,0,0]) cube([80,20,6]);\n    translate([0,35,40]) cube([80,12,6]);\n  }\n  translate([6,5,6]) cube([68,10,4]);\n}\n\nstand();\n`;
  return wrapScaled(scale, body);
}

function templateSculpture(scale) {
  const body = `union() {\n  translate([0,0,0]) sphere(16);\n  translate([20,12,10]) sphere(12);\n  translate([-18,-10,8]) sphere(10);\n  translate([10,-18,6]) sphere(8);\n}\n`;
  return wrapScaled(scale, body);
}

const templates = [
  {
    name: "Jet fighter",
    keywords: ["jet", "fighter", "plane", "aircraft"],
    generator: templateJet,
  },
  {
    name: "Rocket",
    keywords: ["rocket", "missile", "space"],
    generator: templateRocket,
  },
  {
    name: "Desktop computer",
    keywords: ["computer", "monitor", "keyboard", "pc"],
    generator: templateComputer,
  },
  {
    name: "Ring",
    keywords: ["ring", "band", "torus"],
    generator: templateRing,
  },
  {
    name: "Vase",
    keywords: ["vase", "cup", "bowl"],
    generator: templateVase,
  },
  {
    name: "Phone stand",
    keywords: ["phone", "stand", "holder"],
    generator: templatePhoneStand,
  },
  {
    name: "Sculpture",
    keywords: ["sculpture", "abstract", "art"],
    generator: templateSculpture,
  },
];

function pickTemplate(prompt) {
  const lower = prompt.toLowerCase();
  let best = templates[templates.length - 1];
  let bestScore = 0;
  let matches = [];

  templates.forEach((template) => {
    const hits = template.keywords.filter((word) => lower.includes(word));
    if (hits.length > bestScore) {
      bestScore = hits.length;
      best = template;
      matches = hits;
    }
  });

  return { template: best, matches };
}

function generateCode() {
  const rawPrompt = promptInput.value.trim();
  if (!rawPrompt) {
    setStatus("Describe a model before generating.", true);
    setDetails("Waiting for a prompt.");
    output.value = "";
    copyButton.disabled = true;
    openButton.disabled = true;
    return;
  }

  const size = pickSize(rawPrompt, Number(sizeInput.value) || 160);
  sizeInput.value = size;
  const fn = Number(detailInput.value) || 48;
  const scale = clamp(size / 160, 0.2, 4);

  const selection = pickTemplate(rawPrompt);
  const scad = `${baseHeader(fn)}\n${selection.template.generator(scale)}`;

  output.value = scad;
  copyButton.disabled = false;
  openButton.disabled = false;
  setStatus(`Generated ${selection.template.name}.`);
  setDetails(
    selection.matches.length
      ? `Matched keywords: ${selection.matches.join(", ")}.`
      : "No direct match found. Generated a sculpture by default."
  );
}

async function copyCode() {
  const text = output.value;
  if (!text) {
    return;
  }
  try {
    await navigator.clipboard.writeText(text);
    setStatus("Code copied to clipboard.");
  } catch (error) {
    output.focus();
    output.select();
    const succeeded = document.execCommand("copy");
    setStatus(
      succeeded ? "Code copied to clipboard." : "Copy failed. Select and copy manually.",
      !succeeded
    );
  }
}

function openInViewer() {
  const text = output.value;
  if (!text) {
    return;
  }
  localStorage.setItem(STORAGE_KEY, text);
  window.location.href = "index.html#generated";
}

generateButton.addEventListener("click", generateCode);
copyButton.addEventListener("click", copyCode);
openButton.addEventListener("click", openInViewer);
